### ISSUE TITLE
Not able to display

### ISSUE THREAD

**Issue by bhanuteja2001** [krishnaik06/Dockers#3]
![Screenshot (128)](https://user-images.githubusercontent.com/44323155/82864074-45be2000-9f41-11ea-80e9-edad2c65455d.png)

What can be the issue?

**Comment by krishnaik06** [comment]
inside the flask_app.py please change the port number to 8000

**Comment by bhanuteja2001** [comment]
Finally!!!
 I had to change the host to '0.0.0.0' . 
I didn't knew that.
Thank You Krish!!!
