### ISSUE TITLE
Flask URL is not working 

### ISSUE THREAD

**Issue by arpitvw** [krishnaik06/Dockers#4]
docker run -p 9191:9191 money_api

* Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

for all the combination URL is not working
localhost:5000
localhost:9191

0.0.0.0:5000
0.0.0.0:9191

127.0.0.1:5000
127.0.0.1:9191

Note: in docker file, if we give other port also for  Expose apart from 5000 it's running on 5000 port only

**Comment by krishnaik06** [comment]
please use docker ps command and check with port how many containers are running
Then stop all the container by using docker stop containerid

Keep the port to 5000 in the falskapp.py
and map the port from 5000:5000 while running dockers

**Comment by arpitvw** [comment]
Tried that as well but it's not working
changes 
1) flask_api.py :
if __name__=='__main__':
    app.run(port = 5000)
    
2) docker run -p 5000:5000 money_api
3) Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) (Still not working)

**Comment by krishnaik06** [comment]
Use
if __name__=='__main__':
    app.run(host='0.0.0.0',port=5000)

**Comment by arpitvw** [comment]
It worked,
closing the ticket
